version: "3.8"
services:
  tensorflow-jupyterlab:
    build: .
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
